name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install pytest requests

      - name: Run tests
        run: pytest -q

      - name: Run KPI tracker
        run: python tuner_github.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
